spring:
  datasource:
    url: jdbc:mysql://springsecurity.c1c8oe8i8t2b.us-east-1.rds.amazonaws.com/custombank
    username: admin
    password: adminMysql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/custommbankdev/protocol/openid-connect/certs